version: '3.4'

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productdocker
    expose:
      - "3000"
      - "5432"
      - "52120"
    ports:
      - "52120:80"
    networks:
      - hash-network
networks:
  hash-network:
    external: true
